name: saku_mahasiswa
description: "Aplikasi Saku Mahasiswa Luna Oktavia S"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Library grafik untuk tren nilai
  fl_chart: ^0.70.0
  # Library font agar tampilan "aesthetic"
  google_fonts: ^6.2.1
  #Library ikon standar
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/app_icon.jpeg"
    min_sdk_android: 21

flutter:
  # WAJIN TRUE agar ikon PDF dan Tambah Nilai muncul
  uses-material-design: true